Repository thoth-station/thoth-pybench, pull requests merged in 2019-11, with the labels that each got.

#1 Create a release on PyPI
  README
  setup.py
Labels: approved, size/M

#5 Introduce json output
  pybench/pybench.py
Labels: size/M

#6 Update for release
  setup.py
Labels: size/XS

#7 Add inputs to results
  pybench/pybench.py
  setup.py
Labels: size/XS

#8 Remove outputs
  pybench/pybench.py
  setup.py
Labels: size/M

#9 Fix variable name
  pybench/pybench.py
Labels: approved, size/XS

#10 Changes needed for performance indicator
  pybench/CommandLine.py
  pybench/pybench.py
Labels: approved, size/S

#12 new-release-for-pi
  setup.py
Labels: approved, size/XS

#11 Move pybench.py to pybench-cli
  pybench-cli
Labels: size/XS
